### ISSUE TITLE
How to run code via jenkins a a job?

### ISSUE THREAD

**Issue by Singapore-Tech-Entrepreneurs** [Singapore-Tech-Entrepreneurs/jenkins#1]

**Comment by Bisk1** [comment]
In order to run a code via Jenkins job, add a build step "Execute shell" (Linux) or "Execute batch command" (Windows) and invoke python script for comments_remover as follows:
_python_path_ $JENKINS_HOME/comments_remover.py _input_file_path language output_directory_


See _Using as a shell/batch command script_ section of README.md for more details.
